<a href="https://colab.research.google.com/github/mpintoponce/python_utec/blob/main/Modulo02%3AEstructuras_de_datos_secuenciales/08.Evaluaci%C3%B3n_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pregunta N°1**

Crea una lista llamada numeros_pares que contenga los números del 1 al 100 con saltos de 2 en 2.

In [6]:
# Creando una lista vacía
numeros_pares = []

#Agregando números pares a la lista
for i in range(2,102,2):
    numeros_pares.append(i)

#Imprimiento lista
print(numeros_pares)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


**Pregunta N°2**

Agrega los números 102, 104 y 106 al final de la lista numeros_pares y luego elimina los primeros 5 números de la lista numeros_pares. Muestra la lista resultante.

In [3]:
#Agregando números 102, 104 y 106 a la lista
for i in range(102,108,2):
    numeros_pares.append(i)

#Eliminando los primeros 5 números
del numeros_pares[0:5]

#Imprimiento lista
print(numeros_pares)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]


**Pregunta N°3**

Crea una lista llamada resultante que contenga la raíz cuadrada de cada elemento de la lista numeros_pares usando list comprehension.

In [4]:
#Creando lista resultante
resultante = []

#Calculando la raiz cuadrada de cada número
resultante = [round(numeros_pares[num] ** 0.5,2) for num in range(len(numeros_pares))]

#Imprimiento lista
print(numeros_pares)
print(resultante)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]
[3.46, 3.74, 4.0, 4.24, 4.47, 4.69, 4.9, 5.1, 5.29, 5.48, 5.66, 5.83, 6.0, 6.16, 6.32, 6.48, 6.63, 6.78, 6.93, 7.07, 7.21, 7.35, 7.48, 7.62, 7.75, 7.87, 8.0, 8.12, 8.25, 8.37, 8.49, 8.6, 8.72, 8.83, 8.94, 9.06, 9.17, 9.27, 9.38, 9.49, 9.59, 9.7, 9.8, 9.9, 10.0, 10.1, 10.2, 10.3]


**Pregunta N°4**

Dada la siguiente tupla tupla_x = (“alumno”,”Pedro”,15), desempaqueta la tupla tupla_x en tres variables: x, y, z, e imprime la siguiente estructura “El alumno Pedro obtuvo la calificación de 15 usando las variables x, y, z”.

In [30]:
#Creando tupla
tupla_x = ("alumno","Pedro",15)

#Desempaquetando tupla
x,y,z = tupla_x

#Presentando resultado
print(f"El {x} {y} obtuvo la calificación de {z} usando las variables x, y, z")

El alumno Pedro obtuvo la calificación de 15 usando las variables x, y, z


**Pregunta N°5**

Dado el siguiente diccionario notas = {“Programacion”:15.9, “Matematica”: 15.1, “Fisica”:15.6}, escribe un bucle for que imprima cada clave y su valor en el diccionario con la siguiente estructura “Mis calificaciones en el curso de Programacion es 15.9”

In [31]:
#Creando diccionario
notas = {"Programacion":15.9, "Matematica": 15.1, "Fisica":15.6}

#Imprimiendo clave y valor
for clave, valor in notas.items():
    print(f"Mis calificaciones en el curso de {clave} es {valor}")

Mis calificaciones en el curso de Programacion es 15.9
Mis calificaciones en el curso de Matematica es 15.1
Mis calificaciones en el curso de Fisica es 15.6


**Pregunta N°6**

Crea una matriz 1D que contenga los primeros 16 elementos de la lista numeros_pares (creada en la pregunta 1), modifique las dimensiones y convertiela en una matriz 2D con shape(4,4), calcula la suma total de los elementos de la matriz matriz 2D.

In [16]:
#Creando matriz 1D (16 primeros elementos)
matriz_1D = numeros_pares[0:16]

#Convirtiendo en 2D (4x4)
import numpy as np
matriz_2D = np.array(matriz_1D).reshape(4,4)

#Calculando suma total
suma_total = np.sum(matriz_2D)

#Imprimiendo resultados
print(f"La nueva matriz 2D (4x4) es: \n{matriz_2D}")
print(f"\nLa suma de los elementos de la matriz 2D (4x4) es: {suma_total}")

La nueva matriz 2D (4x4) es: 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]

La suma de los elementos de la matriz 2D (4x4) es: 272


**Pregunta N°7**

Leer el archivo datosDemograficos.xlsx y realice un análisis descriptivo en función de las variables más relevantes.

In [19]:
# Conectamos Google Drive con Google Colab
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/gdrive')
ruta = "/gdrive/My Drive/"
dataset = "datosDemograficos (1).xlsx"
data = pd.read_excel(ruta+dataset)

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [23]:
data.shape

(25, 9)

In [24]:
data.head()

Indicadores  Fecundidad  Mortalidad  TasaMortalidadxMil  EsperanzaVida  \
0        Puno       30108        9951                6.86          71.44   
1  San Martín       16074        4889                5.63          72.45   
2       Tacna        5605        1900                5.40          75.11   
3      Tumbes        3924        1209                4.94          74.96   
4     Ucayali        8872        3020                5.93          71.99   

   EVSoloHombres  EVSoloMujeres  TasaMortalidadInfantilxMilNacidos  \
0          68.77          74.25                              26.82   
1          69.65          75.40                              17.53   
2          72.31          78.06                              11.77   
3          72.09          77.98                              11.46   
4          69.24          74.87                              21.07   

   CrecimientoNatural  
0               20157  
1               11185  
2                3705  
3                2715  
4                5852